### ISSUE TITLE
R Implementation for novice

### ISSUE THREAD

**Issue by iwillham** [berenslab/rna-seq-tsne#2]
I have some experience using R (no Python unfortunately) but am having some trouble figuring out how to implement your t-SNE pipeline. In the preprint, you mention that it should be relatively easy to implement in R. What would you recommend as a general approach? Using a Python interface package like reticulate to run the Python functions? Writing an R script de novo to accomplish the same tasks as in the tutorial? Something else? 

I found your explanation of the appropriate uses of t-SNE and tradeoffs in parameter selection to be very intuitive. I hope to work this approach into my normal analysis routine for sc-RNA-Seq data. Any help would be greatly appreciated. Thanks!

**Comment by dkobak** [comment]
@iwilliams91 I am sorry, I haven't noticed your question until right now! Forgot to subscribe to issues. My apologies.

We are using FIt-SNE, and it has R wrapper that is very similar to the Python wrapper. So you can just follow the same steps in R. Let me know if you have more specific questions.

**Comment by dkobak** [comment]
Closed due to inactivity.
